[package]
edition = "2021"
name = "tellyfin_theme"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
# Default enable napi4 feature, see https://nodejs.org/api/n-api.html#node-api-version-matrix
napi = { version = "2.12.2", default-features = false, features = ["experimental", "napi4", "serde-json"] }
napi-derive = "2.12.2"

# Serde
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.8"

# RuSQLite
serde_rusqlite = "0.35.0"
rusqlite = { version = "0.31", features = [
	"bundled",
	"hooks",
	"serde_json",
	"vtab",
	# "csvtab",
	# "uuid",
] }

# Shared utils
util = { path = "../../crates/util" }

[build-dependencies]
napi-build = "2.0.1"

[profile.release]
lto = true
strip = "symbols"
