[package]
edition = "2021"
name = "node-bass"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
# Default enable napi4 feature, see https://nodejs.org/api/n-api.html#node-api-version-matrix
napi = { version = "2.12.2", default-features = false, features = ["napi4"] }
napi-derive = "2.12.2"

serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_repr = "0.1"

bass = { path = "../../crates/bass", features = ["mixer", "cd", "loud", "fx"] }
windows-sys = { version = "0.52.0", features = ["Win32_Foundation", "Win32_UI", "Win32_UI_Input", "Win32_UI_Input_KeyboardAndMouse"] }

once_cell = "1.19.0"

[build-dependencies]
napi-build = "2.0.1"

[profile.release]
lto = true
strip = "symbols"
