/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export const enum FeedbackSound {
  Enter = 'Enter',
  Back = 'Back',
  Move = 'Move',
  MoveCategory = 'MoveCategory',
  Cursor = 'Cursor',
  Ok = 'Ok',
  No = 'No',
  Coldboot = 'Coldboot',
  Gameboot = 'Gameboot'
}
/**
 * IMPORTANT
 *
 * Call this function before anything else!
 */
export declare function initBass(): BassState
export declare class BassState {
  restart(): void
}
export declare class AudioFeedbackManager {
  constructor()
  play(sound: FeedbackSound): void
  playBackground(): void
  stopBackground(): void
}
