[package]
edition = "2021"
name = "mpv"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
# Default enable napi4 feature, see https://nodejs.org/api/n-api.html#node-api-version-matrix
napi = { version = "2.12.2", default-features = false, features = ["experimental", "napi4", "serde-json"] }
napi-derive = "2.12.2"

# MPV dependencies
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_repr = "0.1"
libmpv2 = "3.0.0"
libmpv2-sys = "*"
once_cell = "1.19.0"

[build-dependencies]
napi-build = "2.0.1"

[profile.release]
lto = true
strip = "symbols"
