/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function init(databasePath: string): void
export declare function fetchImage(server: number, callback: (err: Error | null, arg: string) => any): void
